config/routes.rb
Rails.application.routes.draw do
  # get "site/home",
  get "about", to: "site#about"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "quotes#index"

  resources :books
  resources :authors
  resources :quotes

  # Sitemap using sitemap_generator gem
  # get "/sitemap.xml", to: "sitemap#index", defaults: { format: "xml" }

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Keep using helper link_to, seamlessly
  def to_param
    self.slug
  end

  has_many :quotes
  has_many :books

  validates :first_name, presence: true
  # validates :slug, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  include Hasquotes

  # Keep using helper link_to, seamlessly
  def to_param
    self.slug
  end

  belongs_to :author
  has_many :quotes

  validates :title, presence: true
end

app/models/concerns/fetchbookdata.rb
# Fetch book data using literal.club API
module Fetchbookdata
  extend ActiveSupport::Concern

  require 'uri'
  require 'net/http'
  require 'openssl'
  require 'json'
  
  def fetch_book_cover(isbn13)
    url = URI("https://literal.club/graphql/")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    
    request = Net::HTTP::Post.new(url)
    request["Content-Type"] = 'application/json'
    request["User-Agent"] = 'insomnia/10.1.1'
    request.body = "{\n  \"query\": \"query GetBookByIsbn($isbn13: String!) {\\n  book(where: {isbn13: $isbn13}) {\\n    cover\\n  }\\n}\\n\\n\",\n  \"operationName\": \"GetBookByIsbn\",\n  \"variables\": {\n    \"isbn13\": \"#{isbn13}\"\n  }\n}"

    response = http.request(request)
    parsed_response = JSON.parse(response.read_body)

    if parsed_response["data"]["book"]
      return parsed_response["data"]["book"]["cover"]
    end

  end
end

app/models/concerns/hasquotes.rb
module Hasquotes
  extend ActiveSupport::Concern

  # Does this book open with a quote?
  def has_quote?
    @quote = Quote.find_by(book_id: id)
    @quote&.body.present?
  end
end

app/models/concerns/slugs.rb
module Slugs
  extend ActiveSupport::Concern

  def create_slug(name)
    name.downcase.strip.gsub(" ", "-").gsub(/[^\w-]/, "")
  end

  def update_slug
    update_attribute :slug, assign_slug(name)
  end

  private def assign_slug(name)
    self.slug = create_slug(name)
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  # Keep using helper link_to, seamlessly
  def to_param
    self.slug
  end

  belongs_to :book
  belongs_to :author, optional: true

  validates :body, presence: true

  def quote_author
    Author.find_by(id: self.author_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include Slugs

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    # Create a slug for author
    @author.slug = create_slug(@author.first_name + " " + @author.last_name)

    if @author.save
      redirect_to @author
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find_by(slug: params[:id])
  end

  def update
    @author = Author.find_by(slug: params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    # Group authors by first letter of last name
    @initials = Author.order(:last_name).group_by { |u| u.last_name[0] }
  end

  def show
    # Retrieve author based on slug
    @author = Author.find_by(slug: params[:id])
    @author_books = @author.books
    @quotes = Quote.all
    @quoted_quotes = @author.quotes
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :slug)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Slugs
  include Fetchbookdata

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    # Create a slug for book
    @book.slug = create_slug(@book.title)

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find_by(slug: params[:id])
  end

  def update
    @book = Book.find_by(slug: params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @books = Book.order(:title)
  end

  def show
    @book = Book.find_by(slug: params[:id])
    @author = @book.author
    @quotes = @book.quotes
    if (@book.isbn)
      @book_cover = fetch_book_cover(@book.isbn)
    end
  end

  # Like strong type, but for form parameters
  def book_params
    params.require(:book).permit(:title, :year, :author_id, :isbn)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  include Slugs

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    # Create a slug for book
    @quote.slug = create_slug(@quote.body.truncate_words(12))

    if @quote.save
      redirect_to @quote
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @quote = Quote.find_by(slug: params[:id])
  end

  def update
    @quote = Quote.find_by(slug: params[:id])

    if @quote.update(quote_params)
      redirect_to @quote
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @quotes = Quote.order(created_at: :desc)
  end

  def show
    # All the details we need for our quote
    # The quote
    @quote = Quote.find_by(slug: params[:id])
    # The person that put it down
    @quote_author = @quote.author
    # The book where it features
    @parent_book = @quote.book
    # The writer that decided to quote that other author, and that has written the book with this epigraph
    @parent_book_author = @parent_book.author
  end

  # Like strong type, but for form parameters
  def quote_params
    params.require(:quote).permit(:book_id, :body, :author_id)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  # caches_page :about

  def home
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page?(path)
    request.path == path
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/authors/_form.html.erb
<%= form_with model: author do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
    <% author.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
    <% author.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>Authors</h1>
<p>These authors were quoted at the opening of books, have quoted other authors at the opening of their own books, or both.</p>

<div id="author-list">
  <div>
  <% @initials.each do |initial, author| %>
    <h3><%= initial %></h3>
      <ul>
        <% author.each do |a| %>
          <li>
            <%= link_to "#{a.first_name} #{a.last_name}", a %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/authors/new.html.erb
<h1>Add author</h1>

<%= render "form", author: @author %>

app/views/authors/show.html.erb
<h1><%= @author.first_name + " " + @author.last_name %></h1>

<% unless @author_books.length <= 0 %>
    <h2>We have <%= @author_books.length.to_s + " " + "book".pluralize(@author_books.length) %> written by this person containing epigraphs.</h2>
<% end %>

<ul>
    <% @author_books.each do |book| %>
        <li>
            <%= link_to book.title, book %> (<%= book.year %>)
        </li>
    <% end %>
</ul>

<% unless @quoted_quotes.length <= 0 %>
    <h2>This author was quoted <%= @quoted_quotes.length.to_s + " " + "time".pluralize(@quoted_quotes.length) %> in epigraphs.</h2>
    <ul>
        <% @quoted_quotes.each do |quote| %>
            <li>
                <%= link_to quote.body, quote %>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :year %><br>
    <%= form.text_field :year %>
    <% book.errors.full_messages_for(:year).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :isbn %><br>
    <%= form.text_field :isbn %>
    <% book.errors.full_messages_for(:isbn).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>  

  <div>
    <%= form.select :author_id, options_from_collection_for_select(Author.all, 'id', 'last_name') %>
    <% ## form.select :author_id, options_from_collection_for_select(Author.all, 'id', 'name'), { selected: (book.author_id) } %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Books</h1>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book %> (<%= book.year %>)
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>Add book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<div id="book-details">
    <div>
        <h1><%= @book.title %> (<%= @book.year %>)</h1>
        <h2><%= link_to "#{@author.first_name} #{@author.last_name}", @author %></h2>
    </div>
    <% if @book_cover.present? %>
        <img src="<%= @book_cover %>" alt="The cover of the book '<%= @book.title %>'">
    <% end %>
</div>
<% if @book.has_quote? %>
    <br/>
    <p>This book opens with the <%= "epigraph".pluralize(@quotes.length) %>:
    <% @quotes.each do |quote| %>
    
        <h2>"<%= link_to simple_format(quote.body, class: 'quote-body', wrapper_tag: "div"), quote %>"</h2>
        <p>
            — <span class="quote-author"><%= link_to "#{quote.author.first_name} #{quote.author.last_name}", quote.author %></span>
        </p>

    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= content_for(:title) || "Opening Quotes — Unearthing mankind's best quotes, one epigraph at a time." %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta property="og:description" content="Unearthing mankind's best quotes, one epigraph at a time." />
    <meta property="og:url" content="https://openingquot.es/" />
    <meta property="og:site_name" content="Opening Quotes" />
    <meta property="article:publisher" content="https://fredrocha.net" />
    <meta property="og:image" content="https://openingquot.es/og-image.jpg" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta name="twitter:card" content="summary_large_image" /> 

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" %>

    <%= stylesheet_link_tag "application" %>

    <%= javascript_importmap_tags %>

    <!-- Plausible Analytics -->
    <script defer data-domain="openingquot.es" src="https://plausible.io/js/script.outbound-links.js"></script>
    <script>
      window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }
    </script>

  </head>
  <body>
    <header>
      <div id="header-content">
        <div id="header-logo">
          <a href="/">
          <svg viewBox="-1.6 -1.6 19.20 19.20" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#ffffff">
            <g id="SVGRepo_bgCarrier" stroke-width="0">
             <rect x="-1.6" y="-1.6" width="19.20" height="19.20" rx="0" fill="#000000" strokewidth="0"/>
            </g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>
            <g id="SVGRepo_iconCarrier"> <path d="M7 10.4142L2.70711 14.7071L1.29289 13.2929L5 9.58579V9L1 9V2H7V10.4142Z" fill="#000000"/> <path d="M9 9L13 9V9.58579L9.29289 13.2929L10.7071 14.7071L15 10.4142L15 2H9L9 9Z" fill="#000000"/> </g>
          </svg>
          </a>
        </div>
        <div id="main-navigation">
          <ul>
            <li class="<%= 'active' if current_page?('/quotes') %>"><%= link_to 'Quotes', quotes_path %></li>
            <li class="<%= 'active' if current_page?('/books') %>"><%= link_to 'Books', books_path %></li>
            <li class="<%= 'active' if current_page?('/authors') %>"><%= link_to 'Authors', authors_path %></li>
            <li class="<%= 'active' if current_page?('/about') %>"><%= link_to 'About', about_path %></li>
          </ul>
        </div>
      </div>
    </header>
    <div id="body-content">
      <%= yield %>
    </div>
    <footer data-theme="dark">
      <div id="footer-content">
        <div id="footer-logo">
          <a href="/">
            <svg viewBox="-1.6 -1.6 19.20 19.20" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#ffffff">
              <g id="SVGRepo_bgCarrier" stroke-width="0">
              <rect x="-1.6" y="-1.6" width="19.20" height="19.20" rx="0" fill="#000000" strokewidth="0"/>
              </g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>
              <g id="SVGRepo_iconCarrier"> <path d="M7 10.4142L2.70711 14.7071L1.29289 13.2929L5 9.58579V9L1 9V2H7V10.4142Z" fill="#000000"/> <path d="M9 9L13 9V9.58579L9.29289 13.2929L10.7071 14.7071L15 10.4142L15 2H9L9 9Z" fill="#000000"/> </g>
            </svg>
          </a>
        </div>
        <div>
          <p>Unearthing mankind's best quotes, one epigraph at a time. A <a href="https://fredrocha.net" target="_blank">Fred Rocha</a> creative endeavour. The development process is being documented <a href="https://fredrocha.net/2024/08/07/building-a-crud-application-using-ruby-on-rails-in-2024/" target="_blank">here</a>.</p>
          <div id="footer-social-links">
            <p class="social-links">
              <a class="fr-icon" href="https://fredrocha.net" target="_blank">
                <img src="/fr-logo-s.png" alt="Logo for fredrocha.net">
              </a>
              <a class="mastodon-icon" href="https://mastodon.social/@john_fisherman" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 2400 2400"><path d="M288 128C129 128 0 257 0 416v960c0 159 129 288 288 288h960c159 0 288-129 288-288V416c0-159-129-288-288-288H288zm478.38 219.105h3.45c140.347 1.148 275.434 16.34 354.104 52.473 0 0 156.027 69.805 156.027 307.95 0 0 1.957 175.702-21.76 297.69-15.053 77.44-134.816 162.191-272.367 178.616-71.725 8.558-142.346 16.423-217.65 12.969-123.152-5.642-220.329-29.395-220.329-29.395 0 11.989.739 23.404 2.217 34.08 16.01 121.539 120.515 128.819 219.508 132.213 99.915 3.418 188.88-24.633 188.88-24.633l4.106 90.327s-69.885 37.53-194.382 44.431c-68.65 3.774-153.892-1.726-253.174-28.006-215.325-56.993-252.197-286.524-258.022-519.412-1.728-69.147-.665-134.348-.662-188.88.01-238.144 156.033-307.95 156.033-307.95 78.674-36.133 213.675-51.326 354.022-52.473zM607.544 533.18c-50.528 0-91.234 17.76-122.314 52.408-30.14 34.649-45.145 81.48-45.145 140.412v288.354h114.238V734.476c0-59 24.824-88.944 74.477-88.944 54.9 0 82.42 35.524 82.42 105.766V904.49h113.566V751.3c0-70.242 27.516-105.764 82.414-105.764 49.652 0 74.477 29.945 74.477 88.944v279.876h114.238V726.003c0-58.933-14.473-106.234-45.139-140.412-31.086-34.648-71.792-52.408-122.314-52.408-58.466 0-102.735 22.468-132 67.414L768 648.295l-28.455-47.7c-29.271-44.946-73.542-67.415-132.002-67.415z"></path></svg>
              </a>
              <a class="github-icon" href="https://github.com/johnfisherman/openingquot.es" target="_blank">
                <svg fill="none" viewBox="0 0 92 92" width="92" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m45.6097 21.0479c-14.2184 0-25.7347 11.4704-25.7347 25.6323 0 11.3423 7.3666 20.9224 17.5961 24.3187 1.2867.2243 1.7693-.5447 1.7693-1.2176 0-.6087-.0322-2.6273-.0322-4.774-6.4658 1.1855-8.1386-1.57-8.6533-3.0118-.2895-.7369-1.5441-3.0118-2.6378-3.6205-.9007-.4807-2.1875-1.6661-.0322-1.6982 2.0266-.032 3.4742 1.8584 3.9567 2.6273 2.3162 3.8769 6.0155 2.7875 7.4953 2.1147.2251-1.6661.9007-2.7875 1.6406-3.4283-5.726-.6408-11.7093-2.8516-11.7093-12.656 0-2.7875.9972-5.0944 2.6378-6.8887-.2574-.6408-1.1581-3.2681.2573-6.7926 0 0 2.1553-.6728 7.0771 2.6274 2.0587-.5768 4.2462-.8651 6.4336-.8651 2.1875 0 4.3749.2883 6.4337.8651 4.9218-3.3323 7.0771-2.6274 7.0771-2.6274 1.4154 3.5245.5146 6.1518.2573 6.7926 1.6406 1.7943 2.6378 4.0691 2.6378 6.8887 0 9.8364-6.0155 12.0152-11.7414 12.656.9328.801 1.737 2.3389 1.737 4.742 0 3.4283-.0321 6.1838-.0321 7.0488 0 .6729.4825 1.4739 1.7692 1.2176 10.1652-3.3963 17.5318-13.0084 17.5318-24.3187 0-14.1619-11.5163-25.6323-25.7347-25.6323z" fill="#fff" fill-rule="evenodd"/></svg>
              </a>
              </p>
          </div>
        </div>
        <div>
          <p>Consider a small contribution to fuel the expansion of this repository of hand-curated epigraphs.</p>
          <div id="kofi-button-footer" class="kofi-button">
            <a href="https://ko-fi.com/fredrocha" target="_blank">
              <img src="/kofi_button_stroke.webp" />
            </a>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with model: quote do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% quote.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <h4>Book that is opened by epigraph</h4>

  <div>
    <%= form.select :book_id, options_from_collection_for_select(Book.all, 'id', 'title') %>
  </div>

  <h4>Author of this epigraph</h4>

  <div>
    <%= form.select :author_id, options_from_collection_for_select(Author.all, 'id', 'last_name') %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Edit epigraph</h1>

<%= render "form", quote: @quote %>

app/views/quotes/index.html.erb
<h1>Opening Quotes</h1>
<p>This is a collection of quotes that authors choose to open their books with, aka epigraphs. </p>

<ul class="quote-list">
  <% @quotes.each do |quote| %>
    <li>
      "<%= link_to quote.body, quote %>" — <span class="quote-author"><%= "#{quote.quote_author.first_name} #{quote.quote_author.last_name}" %></span>
    </li>
  <% end %>
</ul>

<p>Currently there are <%= @quotes.length %> epigraphs. The list is ever-growing, so make sure to come back.

app/views/quotes/new.html.erb
<h1>Add epigraph</h1>

<%= render "form", quote: @quote %>

app/views/quotes/show.html.erb
<h1>"<%= simple_format(@quote.body, class: 'quote-body', wrapper_tag: "div") %>"</h1>
<p>
    – <span class="quote-author"><%= link_to "#{@quote_author.first_name} #{@quote_author.last_name}", @quote_author %></span>
</p>
<p>Epigraph that opens the book "<%= link_to @parent_book.title, @parent_book %>" by <%= link_to "#{@parent_book_author.first_name} #{@parent_book_author.last_name}", @parent_book_author %>.</p>
<p id="see-more-quotes"><%= link_to "See more quotes", "/quotes" %></p>

app/views/site/about.html.erb
<h1>Why Opening Quotes?</h1>
<div id="about-whats-an-epigraph">
    <div>
        <p>
            Some novelists choose to open their books with a quote from another writer. This is called an <a href="https://en.wikipedia.org/wiki/Epigraph_(literature)" target="_blank">epigraph</a>. 
            These quotes taken out of their original context are given a new life, necessarily detached from the former one. 
            Since writers are the utmost specialists in their fields, and since the beginning of a work has such relevance to the whole, 
            I risk saying that these selected quotes will necessarily be the <i>crème de la crème</i> of World’s Literature.
        </p>
        <p>
            Here we have the epigraph that opens David Sedaris' novel "Happy-Go-Lucky", a quote by Sigmond C. Monster. <a href="/quotes/ban-everything-purify-everything-moral-cleanse-everything-anything-that-was-bad-or">This is how it looks like on this website</a>. Neat, huh?
        </p>
    </div>
    <div>
        <img class="" src="/example-epigraph-happy-go-lucky.jpg" alt="The novel Happy-Go-Lucky is open on a page containing its epigraph." />
    </div>
</div>
<p>
    This website was born as an attempt to document all these priceless and scattered epigraphs in only one place. Welcome!
</p>
<p>
    Plenty of books contain epigraphs, and plenty of folks have contributed with their favorites. The ones with literary, poetic or historical value
    will make it to the website, in an effort to keep the quality of the quotes high. It's a subjective work, but aren't they all?
</p>
<p>
    This is a creative endeavour by <a href="https://fredrocha.net" target="_blank">Fred Rocha</a>, and the development process is being documented
    on <a href="https://fredrocha.net/2024/08/07/building-a-crud-application-using-ruby-on-rails-in-2024/" target="_blank">Fred's website</a>, in case you're curious.  
</p>
<p>
    <a href="mailto:fred@fredrocha.net">Shoot Fred an email</a> (it's fred {[at]} fredrocha.net) if you have a cool epigraph that you'd like to see here, or if you just want to share your thoughts.
</p>
<p>
    This creative endeavour was built from scratch from an idea. The epigraphs database is expanding on a regular basis. If you think this is a worthy project and are feeling generous, you can send a small tip Fred's way. It will help keep the momentum and future creative projects flowing. 
</p>
<p>
    <a href="https://ko-fi.com/fredrocha" target="_blank">
        <img class="kofi-button" src="/kofi_button_red.webp" />
    </a>
</p>
<p>
    Thanks to <a href="https://jamez.it" target="_blank">Giacomo Miceli</a> for reminding me this was a worthwhile pursuit, <a href="https://madalenamarques.com" target="_blank">Madalena Marques</a> for the constant inspiration and out-of-the-box thinking, and Christina Casnellie for the 
    work residency in London, with the best food in town and a steady stream of priceless epigraphs.
</p>
<p>
    Most of these epigraphs were collected directly from books. Some of these epigraphs were salvaged from a previous, like-minded project 
    called Epigraphic, on Tumblr. Hat tip to them.
</p>
<p>
    Book covers are being fetched from <a href="https://literal.club" target="_blank">Literal.club</a>'s API. Thank you, guys!
</p>

app/views/site/home.html.erb
<h1>Site#home</h1>
<p>Find me in app/views/site/home.html.erb</p>